// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRbQRPN1_Zuh47xry5z891c-dxuQELgjE',
    appId: '1:359652393085:web:32ad56097d4d95b21cf114',
    messagingSenderId: '359652393085',
    projectId: 'doan-803f6',
    authDomain: 'doan-803f6.firebaseapp.com',
    storageBucket: 'doan-803f6.firebasestorage.app',
    measurementId: 'G-XGCP49YE00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNoEeMa53YO-0U54GouFMZWXG-BpqmNZU',
    appId: '1:359652393085:android:e32439ec06312f4a1cf114',
    messagingSenderId: '359652393085',
    projectId: 'doan-803f6',
    storageBucket: 'doan-803f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDizOUhSvoUT-3ck-gpCuj0Nb6Tq5RL3yY',
    appId: '1:359652393085:ios:62ede260a3ebb82f1cf114',
    messagingSenderId: '359652393085',
    projectId: 'doan-803f6',
    storageBucket: 'doan-803f6.firebasestorage.app',
    iosClientId: '359652393085-7rbnur344j91otcoknq57m0nqpl1pk69.apps.googleusercontent.com',
    iosBundleId: 'com.example.zingMp3Clone',
  );
}
